use project_sneaker;
SELECT * FROM project_sneaker.customers;

### Objective 1: Analyzing Sales Performance ###
SELECT * FROM project_sneaker.sales;
SELECT * FROM project_sneaker.sales_reprentative;
### 1. What is the total sales amount generated by each sales representative?
select sales_reprentative.salesRepID as Representative, sum(totalAmount)as "Total Sales" from sales join sales_reprentative
on sales.salesRepID= sales_reprentative.salesRepID
group by sales_reprentative.salesRepID order by "Total Sales" desc;

### 2. How many products have been sold in each store location?
select storeLocation as "Location", sum(Quantity)as "product sold" from sales
group by storeLocation order by storeLocation asc;


### 3. Which product category has the highest total sales amount?
select Category, sum(totalAmount)as "Total Sales" from Products join sales
on products.ProductID= sales.ProductID
group by Category order by "Total Sales" desc limit 1;


### 4. What is the average quantity of products sold per sale?
select productName, round(avg(quantity))"Average Sale" from Products join sales
on products.ProductID= sales.ProductID
group by productName;

select Round(AVG((S.Quantity)),0) AS AVG_Product_Per_Sale from sales S;

### 5. Which customer has made the highest number of purchases?
select customers.customerID, concat(FirstName ," ", LastName ) As FullName, Count(customers.saleID) AS Nunber_Of_Purchases from customers join sales 
on customers.customerID=sales.customerID
group by customers.customerID order by Nunber_Of_Purchases desc limit 1;


### 6. What is the distribution of total sales amounts across different months?
select month(sales.Date), sum(TotalAmount)as total_sales from sales 
group by month(sales.Date) order by month(sales.Date) asc;



### 7. How does the sales performance of different regions compare?
select storeLocation, sum(TotalAmount)as total_sales from sales 
group by storeLocation order by storeLocation asc;


### 8. What is the total sales amount generated for each product?
select products.productID, products.ProductName, sum(TotalAmount)as total_sales from products join sales
on products.productID=sales.productID
group by products.productID order by total_sales desc;


### 9. What is the average sales amount per transaction?
select count(saleID)as "Number of transaction", round(sum(totalAmount)/count(saleID))as "Avg sales amount per transaction"from sales;


### 10. How many sales transactions were made by each sales representative?
select sales_reprentative.SalesRepID, concat(FirstName," ",LastName) AS FullName , count(TotalAmount)as "Number of transaction" from sales_reprentative join sales
on sales_reprentative.SalesRepID= sales.SalesRepID
group by sales_reprentative.SalesRepID order by count(TotalAmount) desc, sales_reprentative.SalesRepID asc;
